# Dependabot configuration file
# See docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# This configuration follows the Bayat Development Conventions for dependency management:
# https://github.com/BayatGames/conventions/blob/main/docs/dependencies/management.md
# https://github.com/BayatGames/conventions/blob/main/docs/dependencies/upgrade-strategies.md

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github_actions"
    assignees:
      - "BayatGames/devops"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    assignees:
      - "BayatGames/developers"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for NuGet (.NET)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "nuget"
    assignees:
      - "BayatGames/developers"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      nuget-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for Unity packages
  - package-ecosystem: "npm"
    directory: "/Packages"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "unity"
    assignees:
      - "BayatGames/developers"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      unity-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch" 