name: Organization Metrics Dashboard

on:
  # Schedule updates (every day at midnight)
#   schedule: [{cron: "0 0 * * *"}]
  # Allow manual trigger
  workflow_dispatch:
  # Run on push to main branch (limit to relevant files)
#   push:
#     branches: [main]
#     paths:
#       - '.github/metrics.yml'
#       - '.github/workflows/metrics.yml'

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate organization metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Organization name
          user: ${{ github.repository_owner }}
          # Repository to use (current repository by default)
          repo: ${{ github.repository }}
          # Template (from metrics.yml)
          template: repository
          # Use metrics.yml configuration
          config_gemoji: yes
          config_timezone: UTC
          config_output: svg
          # Output to the repo
          output_action: commit
          # Filename of the output file
          filename: github-metrics.svg
          # Commit message for the output
          committer_message: "chore: update organization metrics dashboard [skip ci]"
          # Use plugins as configured in metrics.yml
          use_prebuilt_image: yes 